### ISSUE TITLE
Update README to follow DT templates

### ISSUE THREAD

**Issue by jeffreyliu** [datatogether/archivertools#10]
We want our documentation to follow the same templates as the rest of Data Together: https://github.com/datatogether/roadmap/tree/master/templates

**Comment by titaniumbones** [comment]
closing as a dupe of #9. Should I leave for you guys or do you want me to take a stab?

**Comment by ebenp** [comment]
If you have time please work on it / close it out! Just figured it was something I could help with later. Go for it!
