### ISSUE TITLE
Add README and Templates

### ISSUE THREAD

**Issue by titaniumbones** [datatogether/archivertools#9]
Make sure this repo has the following files:
- [ ] Readme `README.md`
   - [ ] Repo Badges for: Github Project, Slack, License
   - [ ] 1-3 sentence description of repository contents
   - [ ] Getting Involved section
   - [ ] Development section
- [ ] License -- `LICENSE`
- [ ] Contributing Guidelines (minimal and pointing to org-wide) `.github/CONTRIBUTING.md`
- [ ] Issue Template -- `.github/ISSUE_TEMPLATE.md`
- [ ] GitHub Description from 1-3 sentence readme blurb

This issue forms part of [a project-wide meta-issue](https://github.com/datatogether/roadmap/issues/37)

**Comment by titaniumbones** [comment]
so, went ahead and submitted a PR anyway since I was in the middle of the work. Feel free to ignore & do yrselves if you were already working on it! Did not change README much as it was already petty good by our standards...

**Comment by ebenp** [comment]
Was not working on it, just self assigned as something I could tackle later today. So, great!  Thanks for submitting the PR.  I'll review it this afternoon / evening.

**Comment by jeffreyliu** [comment]
closed via #13
